Sam/create aside component
DaleStudy/leaderboard pull request #81
Opened 2024-11-22 03:49 UTC by SamTheKorean

![Screenshot 2024-11-21 at 10 48 36 PM](https://github.com/user-attachments/assets/f104a963-28d3-4a59-9300-4e693312f1fa)
## 체크리스트

- [ ] 이슈가 연결되어 있나요?

2024-11-23 01:00 UTC, sounmind requested changes

2024-11-23 01:03 UTC, Sunjae95 commented on src/components/Aside/Aside.tsx
> +          </div>
nit) 중복되는 코드가 존재하니 추후에 다른부분만 배열로 바꾸어서 렌더링해도 좋을거 같아요

2024-11-23 18:32 UTC, SamTheKorean commented
실제 데이터 연결까지 완료한 상황입니다! 다만 progress test가 깨져서 공유를 위해 draft pr로 전환하고 푸시했습니다!

2024-11-23 18:35 UTC, SamTheKorean commented on src/components/Progress/Progress.test.tsx
> +test("render the site header", () => {
리더보드에 테스트를 참고해서 작성해봤는데 해당 테스트도 실패해서 공유차원에서 이것만 넣었습니다!

2024-11-26 04:27 UTC, sounmind commented on src/components/Progress/Progress.tsx
> +  ).length;
problems.ts 에서 이 값들을 계산해도 되지 않을까요?

2024-11-26 04:32 UTC, sounmind commented on src/components/Progress/Progress.tsx
> +  const cohort = member.cohort;
```suggestion
  const { grade, cohort } = member;
```

2024-11-26 04:40 UTC, sounmind commented on src/components/Progress/Progress.tsx
> +  const totalSolved = member.solvedProblems.length;
reduce를 사용해서 하나의 객체로 만들어봐도 좋겠네요!

2024-11-27 02:00 UTC, SamTheKorean commented on src/components/Progress/Progress.tsx
> +  const totalSolved = member.solvedProblems.length;
예시까지 감사합니다! 리팩토링해보겠습니다!

2024-11-27 20:40 UTC, SamTheKorean commented on src/components/Progress/Progress.tsx
> +  const profile_url = member.profileUrl || "SampleImg.png";
profile_url이 따로 없을 때는 어떻게 처리하면 좋을까요? 현재는 임의의 이미지를 가져오고 있습니다! @DaleSeo @yolophg

2024-11-28 00:16 UTC, SamTheKorean commented
공유해주신 피드백 반영하고 pr다시 오픈했습니다! 시간내어 피드백주셔서 감사드립니다!

2024-11-28 05:43 UTC, Sunjae95 commented on src/components/Aside/Aside.stories.tsx
> +    ...Default.args,
https://github.com/DaleStudy/leaderboard/pull/72/files#r1845802404
달레님 리뷰개선안인데요. meta에서 args를 선언해주면 매번 초기화를 안할 수 있어요!

2024-11-28 06:08 UTC, Sunjae95 commented on src/components/Progress/Progress.tsx
> +  const hardProgress = `${hardSolved}/${hardProblemsCount}`;
저는 개인적으로 이 로직은 aside에서만 사용하기에 aside에 있어야한다고 생각해요.
왜냐하면 Progress에서 easyProgress, mediumProgress등은 다른 컴포넌트에서 사용하지 않기 때문에 Progress에서 관리할 필요가 없다고 생각합니다. sam님이 보시기엔 어떠신가요??

2024-11-29 02:53 UTC, yolophg commented on src/components/Progress/Progress.tsx
> +  const profile_url = member.profileUrl || "SampleImg.png";
리더보드 전용 기본 이미지를 추가해두었으니, 이걸로 적용해주시면 감사드리겠습니다!
<img width="144" alt="Screenshot 2024-11-28 at 21 49 34" src="https://github.com/user-attachments/assets/76b65d13-08b5-4f71-91ed-d2daf203fa8d">
피그마에 코멘트 남겨두었으니 참고해주세요!

FYI: @DaleSeo @sounmind @Sunjae95 @HC-kang

2024-11-29 03:03 UTC, sounmind commented on src/constants/problems.ts
> +);
👍

2024-11-29 03:06 UTC, sounmind commented on src/components/Progress/Progress.tsx
> +  } = solvedCounts;
```suggestion
  const {
    easy: easySolved,
    medium: mediumSolved,
    hard: hardSolved,
    total: totalSolved,
  } = member.solvedProblems.reduce(
    (acc, problem) => {
      acc[problem.difficulty] = (acc[problem.difficulty] || 0) + 1;
      acc.total += 1;
      return acc;
    },
    { easy: 0, medium: 0, hard: 0, total: 0 },
  );
```

2024-11-29 03:18 UTC, yolophg commented on src/components/Progress/Progress.tsx
> +  const profile_url = member.profileUrl || "SampleImg.png";
위 기본 이미지가 귀엽긴 하나, 기존에 차분하고 클래식한 톤 대비 좀 튀는 것 같기도 하고, '나무'라는 상징성이 드러나는 캐릭터가 등급에 따라 이해하는데 혼동을 줄 수도 있을 것 같아 아래 디자인으로 최종적으로 변경하였습니다. 

기본 이미지가 필요할 시에는 아래 이미지를 사용해주시면 감사드리겠습니다.
<img width="402" alt="Screenshot 2024-11-28 at 22 17 21" src="https://github.com/user-attachments/assets/8ca56815-e3ec-4846-b484-147886eaa5d3">

2024-11-29 05:20 UTC, SamTheKorean commented on src/components/Progress/Progress.tsx
> +  const hardProgress = `${hardSolved}/${hardProblemsCount}`;
피드백 감사합니다! 저는 member를 넘겨주고 aside에 다시 member를 위한 인터페이스를 만들고 또 prop으로 받아서 데이터를 정제해서 사용하는 것보단 member를 page 래밸에서 받아서 필요한 정보들을 내려주는게 더 간단하다고 생각했습니다. Progress 페이지에서 진행상황에 관련된 로직을 처리해주고 aside는 유저 프로필 정보들을 표출하는 것에 초점을 맞춰도 문맥에 어색하지 않다고 느껴집니다. 

추가적으로 아까 테스트 작성의 간편함을 근거로 제시해서 로직을 옮기는 걸 추천해주셨는데 어떤 측면에서 테스트가 용이해지는 막상 코드를 작성하려다 보니 이해가 안됩니다..! 혹시 제가 놓치는게 있다면 피드백 부탁드리겠습니다!

2024-11-29 10:37 UTC, Sunjae95 commented on src/components/Progress/Progress.tsx
> +  const hardProgress = `${hardSolved}/${hardProblemsCount}`;
@SamTheKorean 님 정성스런 코멘트 답변 감사합니다.
저도 항상 컴포넌트 내부에서 데이터를 다룰지 여부를 많이 고민하는데요. 정답은 없는거 같더라구요... sam님께서 작성해주신 이유라면 저역시 동의합니다!

저의 의도는 `find가 완료된 member자체를 props로 받아서 처리해보는건 어떨까요?`라는 질문의도였는데요.

type정의는 기존 api 타입을 prop로 받으면 되는 부분이며 테스트는 member 단일 목데이터를 추가하면 테스트가 용이하다고 생각해요.
테스트 항목은 문제 표기(current/total)을 member만 넣으면 잘 표기되는지를 확인하자였습니다. 그러면 정제되지 않는 데이터가 컴포넌트를 통해 출력을 테스트할 수 있다고 생각해요.

여기까지가 저의 의도였는데, 코멘트달면서 member.solvedProblem의 방대한 목데이터 어떻게 만들지?라고 생각드네요. 현재 sam님께서 작성한 방법이 옳다고 생각합니다!

수고하셨습니다!

2024-11-30 02:30 UTC, Sunjae95 approved these changes

2024-11-30 05:27 UTC, SamTheKorean commented on src/components/Progress/Progress.tsx
> +  const hardProgress = `${hardSolved}/${hardProblemsCount}`;
넵 말씀하신대로 type은 그대로 받으면 되는데 solvedProblem의 목데이터들을 만드는게 번거롭게 느껴지는 것 같아서 제차 질문 드렸습니다! 덕분에 설계에 대해서 다시 한 번 생각해볼 수 있었습니다! 시간내어 피드백 내어 주셔서 감사합니다!

2024-12-01 19:46 UTC, DaleSeo reviewed
스토리북에서 접근성 문제를 보고하고 있는데 확인해주시겠어요?

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/832fedf8-ced6-423a-8035-4d5fe647c9e5">

2024-12-01 19:46 UTC, DaleSeo commented on src/components/Aside/Aside.tsx
> +  profile_url: string;
prop 이름은 camelCase로 일관되게 맞춰주셨으면 좋겠어요.

```suggestion
  profileUrl: string;
```

이미 암묵적으로 따르는 관행인 것 같지만 그래도 관련 내용 기여 가이드에 추가하였습니다.

https://github.com/DaleStudy/leaderboard/wiki/%EA%B8%B0%EC%97%AC-%EA%B0%80%EC%9D%B4%EB%93%9C#%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B5%AC%EC%A1%B0

2024-12-01 19:46 UTC, DaleSeo commented on src/components/Aside/Aside.tsx
> +export default function Aside({
`Aside`는 너무 범용적인 컴포넌트 이름인 것 같아서 `Sidebar`를 제안하고 싶어요.

```suggestion
export default function Sidebar({
```

2024-12-01 19:46 UTC, DaleSeo commented on src/components/Aside/Aside.stories.tsx
> +    profile_url: "https://example.com/profile.jpg", // Provide a valid URL or mock
깨지지 않은 이미지를 사용해주실 수 있을까요? @SamTheKorean 님께서 개발하신 컴포넌트이니 기념하기 위해서 쌤님 프로필 사진을 연결해도 좋을 것 같아요!

![Shot 2024-12-01 at 14 32 31](https://github.com/user-attachments/assets/34877232-523f-4ec0-a248-9915af4366b7)

2024-12-01 19:46 UTC, DaleSeo commented on src/components/Aside/Aside.stories.tsx
> +    ...Default.args,
@SamTheKorean 가능하시다면 위 피드백 좀 follow up 부탁드려도 될까요?

2024-12-01 19:46 UTC, DaleSeo commented on src/assets/Github.png
@Sunjae95 님 PR을 보면 이런 이미지를 인라인 SVG로 처리를 많이 하시는 것 같은데, @SamTheKorean 님께서는 외부 PNG로 처리를 하시네요. 이 부분에 대해서 두 분이 논의한 적이 있나요? 일관적인 방법으로 해야 유지보수가 수월할 것 같습니다.

2024-12-01 19:46 UTC, DaleSeo commented on src/components/Aside/Aside.test.tsx
> +test("renders the Aside component", () => {
이 거 굳이 3개의 테스트 케이스로 나눠서 컴포넌트를 3번씩 렌더링해야 하는가 생각이 드네요? 한 큐에 하셔도 나쁘지 않을 것 같습니다.

2024-12-01 19:46 UTC, DaleSeo commented on src/components/Progress/Progress.test.tsx
> +  vi.stubGlobal("location", {
와, 저 `stubGlobal()` 몰랐습니다. 덕분에 유용한 API 배우고 갑니다! 🙇‍♂️

2024-12-01 19:46 UTC, DaleSeo commented on src/components/Progress/Progress.tsx
> +  } = problemCounts;
이 부분에서 용어의 불일치가 일어나네요. `problem` vs. `task` 저는 둘 다 일리가 된다고 생각하는데, 그래도 용어 통일을 했으면 좋겠습니다.

2024-12-01 20:14 UTC, SamTheKorean commented on src/assets/Github.png
흠 따로 논의한 적은 없지만 저는 card component에 나무들을 png로 받아오시는 걸 보고 암묵적으로 따라가려고 했습니다! @Sunjae95 님 혹시 어느 곳에서는 PNG를 사용하시고 어느 곳에서는 SVG로 처리하신 이유가 있을까요? 기준을 공유해주시면 이견 없이 따라가겠습니다!

2024-12-01 20:15 UTC, SamTheKorean commented on src/components/Progress/Progress.tsx
> +  } = problemCounts;
이 부분을 놓쳤군요! 통일하겠습니다! 리팩토링 과정에서 달라진 것 같습니다! 감사합니다!

2024-12-01 20:16 UTC, SamTheKorean commented on src/components/Aside/Aside.tsx
> +export default function Aside({
사이드바가 더 좋겠네요! 추천감사합니다!

2024-12-01 20:46 UTC, SamTheKorean commented on src/components/Progress/Progress.tsx
> +  } = problemCounts;
problems로 통일했습니다!

2024-12-01 21:35 UTC, SamTheKorean commented
> 스토리북에서 접근성 문제를 보고하고 있는데 확인해주시겠어요?
> 
> <img alt="image" width="1021" src="https://private-user-images.githubusercontent.com/5466341/391358893-832fedf8-ced6-423a-8035-4d5fe647c9e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwODkxMDksIm5iZiI6MTczMzA4ODgwOSwicGF0aCI6Ii81NDY2MzQxLzM5MTM1ODg5My04MzJmZWRmOC1jZWQ2LTQyM2EtODAzNS00ZDVmZTY0N2M5ZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDFUMjEzMzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUyNjUyNDMyNzIwNWU0NDA5Yzk0MjEwMzRlMGZkOTY0YjczYmZjOWJiYTBiODc4OTg0MWFkMTBmMzgwZTkzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.e0EJ_XvMAQU8YjEev9jG_As26h2wO-KqdsmMNdQ6uiI">

위 부분은 sidebar 컴포넌트 뿐만이 아니라 button, card, table 컴포넌트 모두에서 발생하고 있습니다! 색깔 차이가 정도가 일정 기준을 미치지지 못해서 발생하는 이슈로 보입니다! 이부분은 @yolophg 님께서 확인해주실 수 있을까요? 접근성을 맞춘다면 색깔의 변경이 필요해 보입니다!

2024-12-02 00:31 UTC, sounmind approved these changes

2024-12-02 01:18 UTC, SamTheKorean commented
지금 getMember api 리펙토링으로 인해 충돌이 발생하는데 다른 이슈들 해결하고 병합 전에 해결하도록 하겠습니다!

2024-12-02 03:23 UTC, DaleSeo commented
> 위 violation은 sidebar 컴포넌트 뿐만이 아니라 button, card, table 컴포넌트 모두에서 발생하고 있습니다! 색깔 차이가 정도가 일정 기준을 미치지지 못해서 발생하는 이슈로 보입니다! 이부분은 @yolophg 님께서 확인해주실 수 있을까요? 접근성을 맞춘다면 색깔의 변경이 필요해 보입니다!

아 그렇군요. 그럼 본 PR에서 해결이 어렵겠네요. 일단 티켓을 생성해주실 수 있으실까요?

2024-12-02 03:23 UTC, DaleSeo approved these changes
피드백 반영해주셔서 감사합니다.

2024-12-02 03:25 UTC, DaleSeo commented on src/assets/Github.png
@SamTheKorean 아직 제 피드백이 반영되었다고 보기 어려운 것 같습니다. @Sunjae95 님 의견을 주실 때까지는 본 코멘트 쓰레드를  Unresolve 해주실 수 있으실까요?

2024-12-02 03:43 UTC, SamTheKorean commented on src/assets/Github.png
앗 이 부분은 선재님 답변은 기다리는 중이었는데 실수로 눌렀나 봅니다! unresolved 처리 했습니다!

2024-12-03 00:22 UTC, merged